import React from 'react';

const SectionTwo = () => {
    return (
        <>
            <div className="terms-and-conditions-of-use-section-two container">
                <div className="row">
                    <div>
                        <h3 className='mb-4'>TERMINATION OF ACCESS TO ACCOUNT</h3>
                        <p className='para mb-4'>DubyDrive reserves the right to temporarily or permanently suspend access to your Account, with or without prior notice, if in their sole opinion they deem such action necessary to prevent illegal, unauthorized and fraudulent use of the Site.</p>
                        <p className='para mb-4'>DubyDrive may terminate your access to your Account and/or to the Services, in whole or in part, upon notice in the event that: (i) you fail to pay any fees due hereunder to the DubyDrive; (ii) you violate the terms and conditions of this Agreement; (iii) your conduct results in any harm to the DubyDrive or others, cause DubyDrive or others to incur liability, or disrupt DubyDrive's business operations (as determined by DubyDrive in its sole discretion), or affect DubyDrive’s reputation; or (v) for any other lawful reason or as otherwise specified in this Agreement. In such event. We will not refund you any fees paid in advance of such termination, and you shall be obligated to pay all fees and charges accrued prior to the effectiveness of such termination.</p>

                        <h3 className='mb-4 mt-4'>LINKS TO THIRD-PARTY WEBSITES</h3>
                        <p className='para mb-4'>This Site and the Services found at this Site may contain links to third-party websites that are not owned or controlled by the DubyDrive. DubyDrive assumes no responsibility for the content, terms and conditions, privacy policies, or practices of any third-party websites. By using this Site or the Services found at this Site, you expressly release DubyDrive from any and all liability arising from your use of any third-party website. Accordingly, the DubyDrive encourages you to be aware when you leave this Site or the Services found at this Site and to review the terms and conditions, privacy policies, and other governing documents of each other website that you may visit.</p>

                        <h3 className='mb-4 mt-4'>AVAILABILITY OF WEBSITE/SERVICES</h3>
                        <p className='para mb-4'>Subject to the terms and conditions of this Agreement and our other policies and procedures, we shall use commercially reasonable efforts to attempt to provide this Site and the Services on a twenty-four (24) hours a day, seven (7) days a week basis. You acknowledge and agree that from time to time this Site may be inaccessible or inoperable for any reason including, but not limited to, equipment malfunctions; periodic maintenance, repairs or replacements that we undertake from time to time; or causes beyond our reasonable control or that are not reasonably foreseeable including, but not limited to, interruption or failure of telecommunication or digital transmission links, hostile network attacks, network congestion or other failures. You acknowledge and agree that we rely of our service providers for providing these Products and Services and have no control over the availability of this Site or the Service on a continuous or uninterrupted basis, and that we assume no liability to you or any other party with regard thereto. You further acknowledge that we may, under unavoidable circumstances, including but not limited to sandstorms, be forced to delay delivery of the Services. A notice shall reasonably provide the revised date of delivery.</p>

                        <h3 className='mb-4 mt-4'>REPRESENTATIONS AND WARRANTIES</h3>
                        <p className='para mb-4'>You acknowledge and agree that your purchase of the Products or use of the Services, including any information or content obtained through the Services, is at your own risk. You further acknowledge and agree that we exercise no control over, and accept no responsibility for, the content of the information passing through DubyDrive’s network hubs and points of presence or the Internet.</p>

                        <p className='para mb-4'>THIS SITE AND PRODUCTS AND SERVICES FOUND ON THIS SITE ARE PROVIDED ON AN “AS IS”, “AS AVAILABLE BASIS” AND “WITH ALL FAULTS”. DUBYDRIVE AND ITS AFFILIATES, EMPLOYEES, AGENTS, SUPPLIERS AND LICENSORS, DISCLAIM ALL WARRANTIES OF ANY KIND, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT, FOR THE PRODUCTS AND SERVICES PROVIDED HEREUNDER. THE DUBYDRIVE AND ITS AFFILIATES, EMPLOYEES, AGENTS, SUPPLIERS AND LICENSORS MAKE NO REPRESENTATIONS OR WARRANTIES (I) THAT THE SERVICES WILL BE UNINTERRUPTED, ERROR FREE OR COMPLETELY SECURE; (II) AS TO THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE SERVICES; OR (III) AS TO THE ACCURACY, RELIABILITY OR CONTENT OF ANY INFORMATION PROVIDED THROUGH THE SERVICES. THE DUBYDRIVE AND ITS AFFILIATES, EMPLOYEES, AGENTS, SUPPLIERS AND LICENSORS ARE NOT LIABLE, AND EXPRESSLY DISCLAIM ANY LIABILITY, FOR THE CONTENT OF ANY DATA TRANSFERRED EITHER TO OR FROM USERS OR STORED BY USERS ON OR THROUGH THE SERVICES. NO ADVICE OR INFORMATION GIVEN BY DUBYDRIVE OR DUBYDRIVE'S REPRESENTATIVES INCLUDING, WITHOUT LIMITATION, SUPPORT REPRESENTATIVES, SHALL CREATE A WARRANTY. DUBYDRIVE DOES NOT GUARANTEE THAT USERS WILL BE ABLE TO USE THE SERVICES AT TIMES OR LOCATIONS OF THEIR CHOOSING.THE TERMS OF THIS SECTION SHALL SURVIVE ANY TERMINATION OF THIS AGREEMENT.</p>
                        <p className='para mb-4'>You acknowledge and accept that despite the security measures the DubyDrive takes in connection with the Services, DubyDrive’s system may nonetheless become compromised, including without limitation, by hackers, Internet viruses, worms or Trojan horses, or the like. Under such circumstances, DubyDrive may take corrective action as it deems appropriate in its sole discretion and you acknowledge and agree that DubyDrive shall have no liability to you for any damage or loss that you may incur due to such corrective action.</p>

                        <h3 className='mb-4 mt-4'>COMPLIANCE WITH APPLICABLE LAWS</h3>
                        <p className='para mb-4'>You agree to comply with all applicable laws, rules, and regulations applicable to You in regards to your websites, online activities, email and Your use of the Products and Services.</p>

                        <h3 className='mb-4 mt-4'>LIMITATION OF LIABILITY</h3>
                        <p className='para mb-4'>DUBYDRIVE SHALL NOT BE LIABLE FOR NON-PERFORMANCE OR DELAY IN PERFORMANCE CAUSED BY ANY REASON, WHETHER WITHIN OR OUTSIDE OF ITS CONTROL. IN NO EVENT WILL THE DUBYDRIVE ITS OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, AND ALL THIRD PARTY SERVICE PROVIDERS BE LIABLE TO YOU OR ANY THIRD PERSON FOR ANY INDIRECT, CONSEQUENTIAL, EXEMPLARY, INCIDENTAL, SPECIAL OR PUNITIVE DAMAGES, INCLUDING FOR ANY LOST PROFITS OR LOST DATA ARISING FROM YOUR USE OF THE PRODUCTS OR SERVICES, OR ANY CONTENT, EVEN IF DUBYDRIVE IS AWARE OR HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</p>
                        <p className='para mb-4'>NOTWITHSTANDING ANYTHING TO THE CONTRARY CONTAINED HEREIN, DUBYDRIVE'S LIABILITY TO YOU OR ANY PARTY CLAIMING THROUGH YOU FOR ANY CAUSE WHATSOEVER, AND REGARDLESS OF THE FORM OF THE ACTION, SHALL AT ALL TIMES BE LIMITED TO THE AMOUNT PAID, IF ANY, BY YOU TO DUBYDRIVE FOR PRODUCTS PURCHASED OR THE SERVICES PROCURED. THIS IS AN AGGREGATE LIMIT. THE EXISTENCE OF MORE THAN ONE CLAIM HEREUNDER WILL NOT INCREASE THIS LIMIT. NO ACTION, REGARDLESS OF FORM, ARISING OUT OF THIS AGREEMENT OR OUT OF THE SERVICES MAY BE BROUGHT BY YOU, THE USER, MORE THAN THREE (3) YEARS AFTER THE EVENT WHICH GAVE RISE TO THE CAUSE OF ACTION.</p>

                        <h3 className='mb-4 mt-4'>IDENTIFICATION</h3>
                        <p className='para mb-4'>You agree to identify, defend and hold harmless the DubyDrive and its affiliates or its officers, directors, employees, agents and all third party service providers from and against any and all claims, damages, losses, liabilities, suits, actions, demands, proceedings (whether legal or administrative), and expenses (including, but not limited to, reasonable attorney's fees) threatened, asserted, or filed by a third party against the DubyDrive or its officers, directors, employees, agents and/or its third party service providers, arising out of or relating to (i) your purchase of Products or use of the Services, (ii) any breach or violation by you of this Agreement; or (iii) any of your acts or omissions (including without limitation fraud, negligence or wilful misconduct), except to the extent any of the foregoing directly results from DubyDrive's own gross negligence or wilful misconduct. The terms of this section shall survive any termination of this Agreement.</p>

                        <h3 className='mb-4 mt-4'>GOVERNING LAW</h3>
                        <p className='para mb-4'>Any dispute, controversy or claim arising out of or relating to this Agreement, the formation of this Agreement or the breach of this Agreement, including any claim based upon or arising from an alleged tort, shall be governed by the laws of United Arab Emirates in the Emirate of Dubai without giving effect to conflicts of law principles thereof and shall be subject to the exclusive jurisdiction of the Courts in Dubai.</p>

                        <h3 className='mb-4 mt-4'>OTHER GENERAL TERMS</h3>
                        <p className='para mb-4'>DubyDrive and User are independent contractors and nothing contained in this Agreement shall place DubyDrive and Users in the relationship of principal and agent, partners or joint ventures.</p>
                        <p className='para mb-4'>If any provision or portion of any provision of this Agreement shall be held to be illegal, invalid or unenforceable by a court of competent jurisdiction, it is the intention of the parties that the remaining provisions or portions (unless otherwise specified) thereof shall constitute their agreement with respect to the subject matter hereof, and all such remaining provisions or portions (unless otherwise specified) thereof shall remain in full force and effect.</p>
                        <p className='para mb-4'>No failure or delay by any party hereto to exercise any right or remedy hereunder shall operate as a waiver thereof, nor shall any single or partial exercise of any right or remedy by any party preclude any other or further exercise thereof or the exercise of any other right or remedy.</p>
                        <p className='para mb-4'>You may not assign or transfer your obligations, rights and/or duties under this Agreement without the prior written consent of DubyDrive. Any attempted assignment in violation of the foregoing provision shall be null and void and of no force or effect whatsoever. DubyDrive may assign its rights and obligations under this Agreement, and may engage subcontractors or agents in performing its duties and exercising its rights hereunder, without your consent.</p>
                        <p className='para mb-4'>Neither party is liable for any default or delay in the performance of any of its obligations under this Agreement (other than failure to make payments when due) if such default or delay is caused, directly or indirectly, by forces beyond such party's reasonable control, including, without limitation,sandstorms, fire, flood, acts of God, labour disputes, accidents, pandemics, lockdown, acts of war or terrorism, interruptions of transportation or communications, supply shortages, internet outage, technology or network disruptions or the failure of any third party to perform any commitment relative to the production or delivery of any equipment or material required for such party to perform its obligations hereunder.</p>
                        <p className='para mb-4'>Nothing in this Agreement shall be deemed to confer any rights or benefits to any third party.</p>

                        <h3 className='mb-4 mt-4'>MODIFICATION OF AGREEMENT, SITE OR SERVICES</h3>
                        <p className='para mb-4'>DubyDrive may, in its sole and absolute discretion, change or modify this Agreement, and any policies which are incorporated herein, at any time, and such changes or modifications shall be effective immediately upon posting to this Site. Your use of this Site or the Services after such changes or modifications have been made shall constitute your acceptance of this Agreement as last revised. If you do not agree to be bound by this Agreement as last revised, do not use (or continue to use) this Site or the Products or Services. DubyDrive assumes no liability or responsibility for your failure to receive an email notification if such failure results from an inaccurate email address. In addition, DubyDrive may terminate Your use of Services for any violation or breach of any of the terms of this Agreement by You.</p>

                        <h3 className='mb-4 mt-4'>CONTACT INFORMATION</h3>
                        <p className='para mb-4'>If you have any questions about this Agreement, please contact at : <b>info@Dubydrive.com</b></p>
                    </div>
                </div>
            </div>
        </>
    );
};

export default SectionTwo;