import React from 'react';

const SectionOne = () => {
    return (
        <>
            <div className="terms-and-conditions-of-use-section-one container pt-5 pb-3">
                <div className="row">
                    <div>
                        <h1 className='primary_text_color mb-4'>Terms of Use</h1>
                    </div>

                    <div>
                        <p className='para mb-4'>Duby Drive, also known as  DubyDrive Portal, is a UAE-based company that owns and operates the website www.dubydrive.com. We kindly ask you to carefully read the following terms and conditions. By accessing and using this website, you agree to be bound by these terms. If you do not agree with these terms, we ask that you do not use this site. These terms and conditions take precedence over any other agreements unless otherwise agreed upon in writing. DubyDrive reserves the right to revise these terms and conditions at any time, so we encourage you to review them regularly.</p>
                        <p className='para mb-4'>On the date of electronic acceptance of these Terms of Use, it shall be deemed that You have entered into a formal binding agreement with the DubyDrive. This Agreement sets forth the general terms and conditions for your use of the Site and for procuring the products/services offered on this Site (the “Services”).</p>

                        <h3 className='mb-4 mt-4'>1. ELIGIBILITY</h3>
                        <p className='para mb-4'>This Site and the Services are available only to individuals or entities (“Users”) who can form legally binding contracts under laws of United Arab Emirates. The Services are intended solely for users who are eighteen (18) years of age or older. Any registration by, use of or access to the Services by anyone under eighteen (18) is unauthorized and in violation of this Agreement. As a minor, if you wish to use or transact on the Site, such use or transaction may be made only in the presence of and through your legal guardian or parents. We reserve our right to terminate the Services and / or refuse to provide you with access to the Site if it is brought to our notice or if it is discovered that you are under the age of 18 years.</p>
                        <p className='para mb-4'>If you are entering into this Agreement on behalf of a corporate entity or other organization, you represent and warrant that you have the legal authority to bind such corporate entity or organization to these terms and conditions contained herein, in which case the terms "You", "Your", "User" shall refer to such corporate entity or organisation.</p>

                        <h3 className='mb-4 mt-4'>2. YOUR ACCOUNT</h3>
                        <p className='para mb-4'>In order to access some of the features of this Site, purchase products or use some of the Services, you will have to get registered. You represent and warrant to DubyDrive that all information you submit about you and your organization (if applicable) as prompted by the registration forms when you create your Account, is accurate, current and complete, and that you will keep your information up to date and complete. If DubyDrive has reason to believe that your Account information is untrue, inaccurate, out-of-date or incomplete, DubyDrive reserves the right, in its sole and absolute discretion, to suspend or terminate your Account. You are solely responsible for the activity that occurs on your Account, whether authorized by you or not, and you must maintain utmost confidentiality of your Account information, including without limitation your login, password, Payment Method(s) (as defined below). You must notify us immediately of any breach of security or unauthorized use of your Account. DubyDrive will not be liable for any loss you incur due to any unauthorized use of your Account.</p>

                        <h3 className='mb-4 mt-4'>3. CONTENT</h3>
                        <p className='para mb-4'>Except for User Submissions (as defined below), all content available through the Products, Services, including designs, text, graphics, images, video, information, software, audio and other files, and their selection and arrangement, and all software used to provide the Products or Services (collectively, " DubyDrive’s Content"), are the property of DubyDrive or its licensors and no rights in the DubyDrive’s Content are deemed granted to you, unless expressly stated under this Agreement. No DubyDrive’s Content may be modified, copied, distributed, framed, reproduced, republished, downloaded, scraped, displayed, posted, transmitted, sold or exploited for any purpose in any form or by any means, in whole or in part, other than as expressly permitted in this Agreement. You may not, directly or indirectly, reverse engineer, decompile, disassemble or otherwise attempt to derive source code or other trade secrets from any DubyDrive’s Content. Any use of the DubyDrive’s Content other than as specifically authorized herein is prohibited and will automatically terminate your rights with respect to your use of the Services and the DubyDrive’s Content granted herein. All rights of DubyDrive or its licensors that are not expressly granted in this Agreement are reserved to the DubyDrive and its licensors. You hereby acknowledge that the DubyDrive may use text, images, videos or other content in any of the Services provided to you, however, such content maybe procured from third party and shall be subject to the applicable third party’s terms and conditions.</p>

                        <p className='para mb-4'>User Submissions: You acknowledge and agree that User Submissions made by you on publicly viewable sections of the Site, are entirely voluntary and do not establish a confidential relationship or obligate the DubyDrive to treat such User Submissions as confidential or secret. DubyDrive has no obligation, either express or implied, to develop or use your User Submissions, and no compensation is due to you or to anyone else for any intentional or unintentional use of your User Submissions. DubyDrive shall own exclusive rights (including all intellectual property and other proprietary rights) to any User Submissions posted to this Site, and shall be entitled to the unrestricted use and dissemination of any User Submissions posted to this Site for any purpose, commercial or otherwise, without acknowledgment or compensation to you or to anyone else.</p>

                        <p className='para mb-4'>Additional data shared. You may be required to provide additional data to support Your requirement or for the DubyDrive to fulfil Your service request or place order for Services. In all such cases, such additional data may uploaded onto the Site in such format as instructed by DubyDrive. You acknowledge and undertake not to upload any file or data that may contain any virus, trojan, worm, spyware, malware, firmware, ransomware or any other such hidden codes intended to disrupt the Site or to illegally gather data and information from DubyDrive (collectively Malicious Codes). DubyDrive reserves the right to refrain from accepting any such file that is marked as hazardous or potential security threat to DubyDrive. DubyDrive further reserves its right to initiate appropriate legal proceedings against You in case they perceive that You have intentionally attempted to upload any such Malicious Codes.</p>

                        <h3 className='mb-4 mt-4'>4. PRIVACY</h3>
                        <p className='para mb-4'>We care about the privacy of our Users. The DubyDrive’s Privacy Policy (the “Privacy Policy”) governs use of data and information provided to DubyDrive by you. By accepting this Agreement, you also acknowledge that you have read and agree to the terms of the Privacy Policy.</p>

                        <h3 className='mb-4 mt-4'>5. SECURITY</h3>
                        <p className='para mb-4'>You acknowledge and accept that despite the security measures DubyDrive takes in connection with the Services, DubyDrive’s systems may nonetheless become compromised, including without limitation, by hackers, Internet viruses, worms or Trojan horses, or the like. Under such circumstances, DubyDrive may take corrective actions as it deems appropriate in its sole discretion and you acknowledge and agree that DubyDrive shall have no liability to you for any damage or loss that you may incur due to such corrective action.</p>
                        <p className='para mb-4'>Your further acknowledge that We may, in our sole discretion, agree to provide necessary information or assistance as may be required by an applicable governmental authority or court, concerning cyber security or security of the state, investigation, detection, prosecution, or prevention of offences.</p>
                        <p className='para mb-4'>We will provide technical support via email for the Services (“Technical Support Services”). You will be required to provide as much information as possible to aid our investigation into any issues or problems.</p>

                        <h3 className='mb-4 mt-4'>6. ADDITIONAL USER RESPONSIBILITIES</h3>
                        <p className='para mb-4'>You will be solely responsible for all activities conducted on or through Your Account, including initiating any transactions or discussions with us. You shall solely be responsible for any illegal use of the Products or Services. DubyDrive shall at no time be responsible to ascertain the intent of purchase of Products or requesting for the Services.</p>
                        <p className='para mb-4'>You will use your best efforts to ensure that the content and other materials you intend to provide to us is and will at all times remain free of all computer viruses, worms, Trojan horses and other malicious code.</p>
                        <p className='para mb-4'>You will not use the Services in any manner infringe the intellectual property rights or other proprietary rights of any third party or with the intention of violating the privacy rights or publicity rights of any third party.</p>

                        <h3 className='mb-4 mt-4'>7. PAYMENT</h3>
                        <p className='para mb-4'>You agree to pay such prices or fees as mentioned against various Products or Services selected by You from the Site. All prices or fees are non-refundable when paid except as otherwise provided in the payment terms related to the Product or Service. We may change our prices from time to time, and such changes shall be posted online at this Site and effective immediately without need for further notice to you. If you have purchased or obtained any Services for a period of months or years, changes in prices and fees shall be effective when the Services in question come up for renewal as further described in the payment terms related to the Service.</p>

                        <h3 className='mb-4 mt-4 primary_text_color'>Taxes</h3>
                        <p className='para mb-4'>The fee is exclusive of any applicable goods and service taxes (GST) and any other tax imposed by any authority with respect to the Services.</p>

                        <h3 className='mb-4 mt-4 primary_text_color'>Cancellation and Refund Policy</h3>
                        <p className='para mb-4'>In case where you wish to cancel a booking, it is mandatory for you to notify us at least before 24 (twenty four) hours of the scheduled time. A nominal amount shall be deducted towards cancellation fees and the balance shall be refunded to the original mode of payment within 10 (ten) to 45 (forty five) days depending on the issuing bank of the credit card. If you fail to notify us within the prescribed time limit, we shall be entitled to deduct the entire amount and no refund shall be made. In case of other queries, please contact us at : <b>info@Dubydrive.com</b></p>

                        <h3 className='mb-4 mt-4 primary_text_color'>Failure to Pay</h3>
                        <p className='para mb-4'>If you fail to pay the fees due for the Services, we may suspend or terminate your Services and pursue any collection costs incurred by the DubyDrive, including without limitation, any arbitration and legal fees and DubyDrive's reasonable attorneys' fees. Accounts or subscriptions will not be reactivated until all outstanding amounts are paid. We are not responsible for any deleted or lost content that was provided by You, as a result of any suspension or termination of the Services.</p>
                    </div>
                </div>
            </div>
        </>
    );
};

export default SectionOne;